# Generated by Django 3.2.10 on 2022-03-27 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50, verbose_name='Track name')),
                ('source', models.FileField(upload_to='main/static/tracks/', validators=[userprofile.validators.validate_file_extension], verbose_name='Source')),
                ('genre', models.CharField(default='None', max_length=50, verbose_name='Genre')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('auditions', models.IntegerField(null=True, verbose_name='Auditions')),
                ('date', models.DateField(null=True, verbose_name='Release date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
