# Generated by Django 3.2.12 on 2022-05-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='duration',
        ),
        migrations.AlterField(
            model_name='tracks',
            name='source',
            field=models.FileField(upload_to='sounds/', validators=[userprofile.validators.validate_file_extension], verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='avatars/', verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
