# Generated by Django 3.2.12 on 2022-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20220504_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='auditions',
            field=models.IntegerField(default=0, null=True, verbose_name='Auditions'),
        ),
    ]
