# Generated by Django 3.2.12 on 2022-02-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('mail', models.CharField(max_length=50, verbose_name='Mail')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
            ],
        ),
    ]
