# Generated by Django 3.2.12 on 2022-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mynewuser', '0003_delete_db_freelabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('mail', models.CharField(max_length=50, verbose_name='mail')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
            ],
        ),
    ]
