# Generated by Django 3.2.12 on 2022-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewuser', '0006_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='user', max_length=15, verbose_name='status'),
        ),
    ]
